version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/welsh-academy/.
  build:
    cmds:
      - go build -o ./bin/welsh-academy ./cmd/welsh-academy/.
  docker-build:
      - docker build . -t welsh-academy 
  docker-run:
      deps: [docker-build]
      cmds:
          - docker run -p 9000:9000 {{.CLI_ARGS}} welsh-academy
  generate-swagger-doc:
    aliases: [gen-swagger]
    cmds: 
      - swag init -g cmd/welsh-academy/main.go --parseDependency --parseInternal
  test:
    cmds:
      - cmd: go test ./... -cover
        ignore_error: true
  coverage:
      - go test ./... -coverprofile=coverage.out
        
